--------------------------------------------------------
--  File created - czwartek-lipca-02-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PRACOWNICY
--------------------------------------------------------

  CREATE TABLE "SOURCE2"."PRACOWNICY" SHARING=METADATA 
   (	"ID_PRACOWNIKA" NUMBER, 
	"IMIE" VARCHAR2(60 BYTE), 
	"NAZWISKO" VARCHAR2(2060 BYTE), 
	"DATA_ZATRUDNIENIA" DATE, 
	"DATA_ZWOLNIENIA" DATE, 
	"PESEL" VARCHAR2(11 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PREMIA
--------------------------------------------------------

  CREATE TABLE "SOURCE2"."PREMIA" SHARING=METADATA 
   (	"ID_PREMIA" NUMBER, 
	"ID_PRACOWNIK" NUMBER, 
	"WYSOKOSC" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZASILEK
--------------------------------------------------------

  CREATE TABLE "SOURCE2"."ZASILEK" SHARING=METADATA 
   (	"ID_ZASILEK" NUMBER, 
	"ID_PRACOWNIK" NUMBER, 
	"ID_ZASILEK_DETALE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZASILEK_DETALE
--------------------------------------------------------

  CREATE TABLE "SOURCE2"."ZASILEK_DETALE" SHARING=METADATA 
   (	"ID_ZASILEK_DETALE" NUMBER, 
	"KWOTA" NUMBER, 
	"DATA" DATE, 
	"NAZWA" VARCHAR2(90 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SOURCE2.PRACOWNICY
SET DEFINE OFF;
Insert into SOURCE2.PRACOWNICY (ID_PRACOWNIKA,IMIE,NAZWISKO,DATA_ZATRUDNIENIA,DATA_ZWOLNIENIA,PESEL) values ('102','Janusz','Adamczyk',to_date('12/10/10 00:00','RR/MM/DD HH24:MI'),to_date('99/12/31 00:00','RR/MM/DD HH24:MI'),'95010433717');
Insert into SOURCE2.PRACOWNICY (ID_PRACOWNIKA,IMIE,NAZWISKO,DATA_ZATRUDNIENIA,DATA_ZWOLNIENIA,PESEL) values ('103','Maciej','Szymanski',to_date('16/02/15 00:00','RR/MM/DD HH24:MI'),to_date('99/12/31 00:00','RR/MM/DD HH24:MI'),'97112714299');
Insert into SOURCE2.PRACOWNICY (ID_PRACOWNIKA,IMIE,NAZWISKO,DATA_ZATRUDNIENIA,DATA_ZWOLNIENIA,PESEL) values ('104','Joanna','Kaliszuk',to_date('19/11/25 00:00','RR/MM/DD HH24:MI'),to_date('99/12/31 00:00','RR/MM/DD HH24:MI'),'86090469183');
Insert into SOURCE2.PRACOWNICY (ID_PRACOWNIKA,IMIE,NAZWISKO,DATA_ZATRUDNIENIA,DATA_ZWOLNIENIA,PESEL) values ('105','Cezary','Pietrzyk',to_date('15/12/05 00:00','RR/MM/DD HH24:MI'),to_date('99/12/31 00:00','RR/MM/DD HH24:MI'),'72112348314');
REM INSERTING into SOURCE2.PREMIA
SET DEFINE OFF;
Insert into SOURCE2.PREMIA (ID_PREMIA,ID_PRACOWNIK,WYSOKOSC) values ('771','102','3000');
Insert into SOURCE2.PREMIA (ID_PREMIA,ID_PRACOWNIK,WYSOKOSC) values ('772','103','1000');
REM INSERTING into SOURCE2.ZASILEK
SET DEFINE OFF;
Insert into SOURCE2.ZASILEK (ID_ZASILEK,ID_PRACOWNIK,ID_ZASILEK_DETALE) values ('5','102','11');
Insert into SOURCE2.ZASILEK (ID_ZASILEK,ID_PRACOWNIK,ID_ZASILEK_DETALE) values ('8','103','12');
Insert into SOURCE2.ZASILEK (ID_ZASILEK,ID_PRACOWNIK,ID_ZASILEK_DETALE) values ('9','104','13');
Insert into SOURCE2.ZASILEK (ID_ZASILEK,ID_PRACOWNIK,ID_ZASILEK_DETALE) values ('10','104','14');
REM INSERTING into SOURCE2.ZASILEK_DETALE
SET DEFINE OFF;
Insert into SOURCE2.ZASILEK_DETALE (ID_ZASILEK_DETALE,KWOTA,DATA,NAZWA) values ('11','100',to_date('20/07/01 12:53','RR/MM/DD HH24:MI'),'Pomoc socjalna');
Insert into SOURCE2.ZASILEK_DETALE (ID_ZASILEK_DETALE,KWOTA,DATA,NAZWA) values ('12','100',to_date('20/07/01 12:53','RR/MM/DD HH24:MI'),'Pomoc socjalna');
Insert into SOURCE2.ZASILEK_DETALE (ID_ZASILEK_DETALE,KWOTA,DATA,NAZWA) values ('13','1000',to_date('19/12/20 00:00','RR/MM/DD HH24:MI'),'Pomoc socjalna');
Insert into SOURCE2.ZASILEK_DETALE (ID_ZASILEK_DETALE,KWOTA,DATA,NAZWA) values ('14','1500',to_date('19/12/25 00:00','RR/MM/DD HH24:MI'),'Pomoc socjalna');
--------------------------------------------------------
--  Constraints for Table PRACOWNICY
--------------------------------------------------------

  ALTER TABLE "SOURCE2"."PRACOWNICY" MODIFY ("ID_PRACOWNIKA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PREMIA
--------------------------------------------------------

  ALTER TABLE "SOURCE2"."PREMIA" MODIFY ("ID_PREMIA" NOT NULL ENABLE);
  ALTER TABLE "SOURCE2"."PREMIA" MODIFY ("ID_PRACOWNIK" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ZASILEK
--------------------------------------------------------

  ALTER TABLE "SOURCE2"."ZASILEK" MODIFY ("ID_ZASILEK" NOT NULL ENABLE);
  ALTER TABLE "SOURCE2"."ZASILEK" MODIFY ("ID_PRACOWNIK" NOT NULL ENABLE);
  ALTER TABLE "SOURCE2"."ZASILEK" MODIFY ("ID_ZASILEK_DETALE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ZASILEK_DETALE
--------------------------------------------------------

  ALTER TABLE "SOURCE2"."ZASILEK_DETALE" MODIFY ("ID_ZASILEK_DETALE" NOT NULL ENABLE);
