--------------------------------------------------------
--  File created - czwartek-lipca-02-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table KLIENCI_BAD
--------------------------------------------------------

  CREATE TABLE "TEMP"."KLIENCI_BAD" 
   (	"ID_KLIENT" NUMBER, 
	"IMIE" VARCHAR2(60 BYTE), 
	"NAZWISKO" VARCHAR2(60 BYTE), 
	"ULICA" VARCHAR2(90 BYTE), 
	"NR_MIESZKANIA" VARCHAR2(20 BYTE), 
	"POCZTA" VARCHAR2(60 BYTE), 
	"NR_TELEFONU" VARCHAR2(11 BYTE), 
	"START_DTTM" DATE, 
	"END_DTTM" DATE, 
	"SOURCE_ID" NUMBER, 
	"SYSTEM_ID" VARCHAR2(255 BYTE), 
	"UNIEWAZNIONY" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KLIENCI_DELTA
--------------------------------------------------------

  CREATE TABLE "TEMP"."KLIENCI_DELTA" 
   (	"ID_KLIENT" NUMBER, 
	"IMIE" VARCHAR2(60 BYTE), 
	"NAZWISKO" VARCHAR2(60 BYTE), 
	"ULICA" VARCHAR2(90 BYTE), 
	"NR_MIESZKANIA" VARCHAR2(20 BYTE), 
	"POCZTA" VARCHAR2(60 BYTE), 
	"NR_TELEFONU" VARCHAR2(11 BYTE), 
	"START_DTTM" DATE, 
	"END_DTTM" DATE, 
	"SOURCE_ID" NUMBER, 
	"SYSTEM_ID" VARCHAR2(255 BYTE), 
	"UNIEWAZNIONY" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KLIENCI_TMP
--------------------------------------------------------

  CREATE TABLE "TEMP"."KLIENCI_TMP" 
   (	"ID_KLIENT" NUMBER, 
	"IMIE" VARCHAR2(60 BYTE), 
	"NAZWISKO" VARCHAR2(60 BYTE), 
	"ULICA" VARCHAR2(90 BYTE), 
	"NR_MIESZKANIA" VARCHAR2(20 BYTE), 
	"POCZTA" VARCHAR2(60 BYTE), 
	"NR_TELEFONU" VARCHAR2(11 BYTE), 
	"START_DTTM" DATE, 
	"END_DTTM" DATE, 
	"SOURCE_ID" NUMBER, 
	"SYSTEM_ID" VARCHAR2(255 BYTE), 
	"UNIEWAZNIONY" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRACOWNICY_BAD
--------------------------------------------------------

  CREATE TABLE "TEMP"."PRACOWNICY_BAD" 
   (	"ID_PRACOWNIKA" NUMBER, 
	"IMIE" VARCHAR2(60 BYTE), 
	"NAZWISKO" VARCHAR2(2060 BYTE), 
	"DATA_ZATRUDNIENIA" DATE, 
	"DATA_ZWOLNIENIA" DATE, 
	"PESEL" VARCHAR2(11 BYTE), 
	"START_DTTM" DATE, 
	"END_DTTM" DATE, 
	"SOURCE_ID" NUMBER, 
	"SYSTEM_ID" VARCHAR2(255 BYTE), 
	"UNIEWAZNIONY" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRACOWNICY_DELTA
--------------------------------------------------------

  CREATE TABLE "TEMP"."PRACOWNICY_DELTA" 
   (	"ID_PRACOWNIKA" NUMBER, 
	"IMIE" VARCHAR2(60 BYTE), 
	"NAZWISKO" VARCHAR2(2060 BYTE), 
	"DATA_ZATRUDNIENIA" DATE, 
	"DATA_ZWOLNIENIA" DATE, 
	"PESEL" VARCHAR2(11 BYTE), 
	"START_DTTM" DATE, 
	"END_DTTM" DATE, 
	"SOURCE_ID" NUMBER, 
	"SYSTEM_ID" VARCHAR2(255 BYTE), 
	"UNIEWAZNIONY" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRACOWNICY_TMP
--------------------------------------------------------

  CREATE TABLE "TEMP"."PRACOWNICY_TMP" 
   (	"ID_PRACOWNIKA" NUMBER, 
	"IMIE" VARCHAR2(60 BYTE), 
	"NAZWISKO" VARCHAR2(2060 BYTE), 
	"DATA_ZATRUDNIENIA" DATE, 
	"DATA_ZWOLNIENIA" DATE, 
	"PESEL" VARCHAR2(11 BYTE), 
	"START_DTTM" DATE, 
	"END_DTTM" DATE, 
	"SOURCE_ID" NUMBER, 
	"SYSTEM_ID" VARCHAR2(255 BYTE), 
	"UNIEWAZNIONY" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PREMIA_BAD
--------------------------------------------------------

  CREATE TABLE "TEMP"."PREMIA_BAD" 
   (	"ID_PREMIA" NUMBER, 
	"ID_PRACOWNIK" NUMBER, 
	"WYSOKOSC" NUMBER, 
	"START_DTTM" DATE, 
	"END_DTTM" DATE, 
	"SOURCE_ID" NUMBER, 
	"SYSTEM_ID" VARCHAR2(255 BYTE), 
	"UNIEWAZNIONY" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PREMIA_DELTA
--------------------------------------------------------

  CREATE TABLE "TEMP"."PREMIA_DELTA" 
   (	"ID_PREMIA" NUMBER, 
	"ID_PRACOWNIK" NUMBER, 
	"WYSOKOSC" NUMBER, 
	"START_DTTM" DATE, 
	"END_DTTM" DATE, 
	"SOURCE_ID" NUMBER, 
	"SYSTEM_ID" VARCHAR2(255 BYTE), 
	"UNIEWAZNIONY" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PREMIA_TMP
--------------------------------------------------------

  CREATE TABLE "TEMP"."PREMIA_TMP" 
   (	"ID_PREMIA" NUMBER, 
	"ID_PRACOWNIK" NUMBER, 
	"WYSOKOSC" NUMBER, 
	"START_DTTM" DATE, 
	"END_DTTM" DATE, 
	"SOURCE_ID" NUMBER, 
	"SYSTEM_ID" VARCHAR2(255 BYTE), 
	"UNIEWAZNIONY" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZAMOWIENIE_BAD
--------------------------------------------------------

  CREATE TABLE "TEMP"."ZAMOWIENIE_BAD" 
   (	"ID_ZAMOWIENIE" NUMBER, 
	"ID_KLIENT" NUMBER, 
	"ID_PRACOWNIK" NUMBER, 
	"DATA" DATE, 
	"START_DTTM" DATE, 
	"END_DTTM" DATE, 
	"SOURCE_ID" NUMBER, 
	"SYSTEM_ID" VARCHAR2(255 BYTE), 
	"UNIEWAZNIONY" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZAMOWIENIE_DELTA
--------------------------------------------------------

  CREATE TABLE "TEMP"."ZAMOWIENIE_DELTA" 
   (	"ID_ZAMOWIENIE" NUMBER, 
	"ID_KLIENT" NUMBER, 
	"ID_PRACOWNIK" NUMBER, 
	"DATA" DATE, 
	"START_DTTM" DATE, 
	"END_DTTM" DATE, 
	"SOURCE_ID" NUMBER, 
	"SYSTEM_ID" VARCHAR2(255 BYTE), 
	"UNIEWAZNIONY" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZAMOWIENIE_TMP
--------------------------------------------------------

  CREATE TABLE "TEMP"."ZAMOWIENIE_TMP" 
   (	"ID_ZAMOWIENIE" NUMBER, 
	"ID_KLIENT" NUMBER, 
	"ID_PRACOWNIK" NUMBER, 
	"DATA" DATE, 
	"START_DTTM" DATE, 
	"END_DTTM" DATE, 
	"SOURCE_ID" NUMBER, 
	"SYSTEM_ID" VARCHAR2(255 BYTE), 
	"UNIEWAZNIONY" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZASILEK_BAD
--------------------------------------------------------

  CREATE TABLE "TEMP"."ZASILEK_BAD" 
   (	"ID_ZASILEK" NUMBER, 
	"ID_PRACOWNIK" NUMBER, 
	"ID_ZASILEK_DETALE" NUMBER, 
	"START_DTTM" DATE, 
	"END_DTTM" DATE, 
	"SOURCE_ID" NUMBER, 
	"SYSTEM_ID" VARCHAR2(255 BYTE), 
	"UNIEWAZNIONY" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZASILEK_DELTA
--------------------------------------------------------

  CREATE TABLE "TEMP"."ZASILEK_DELTA" 
   (	"ID_ZASILEK" NUMBER, 
	"ID_PRACOWNIK" NUMBER, 
	"ID_ZASILEK_DETALE" NUMBER, 
	"START_DTTM" DATE, 
	"END_DTTM" DATE, 
	"SOURCE_ID" NUMBER, 
	"SYSTEM_ID" VARCHAR2(255 BYTE), 
	"UNIEWAZNIONY" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZASILEK_DETALE_BAD
--------------------------------------------------------

  CREATE TABLE "TEMP"."ZASILEK_DETALE_BAD" 
   (	"ID_ZASILEK_DETALE" NUMBER, 
	"KWOTA" NUMBER, 
	"DATA" DATE, 
	"NAZWA" VARCHAR2(90 BYTE), 
	"START_DTTM" DATE, 
	"END_DTTM" DATE, 
	"SOURCE_ID" NUMBER, 
	"SYSTEM_ID" VARCHAR2(255 BYTE), 
	"UNIEWAZNIONY" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZASILEK_DETALE_DELTA
--------------------------------------------------------

  CREATE TABLE "TEMP"."ZASILEK_DETALE_DELTA" 
   (	"ID_ZASILEK_DETALE" NUMBER, 
	"KWOTA" NUMBER, 
	"DATA" DATE, 
	"NAZWA" VARCHAR2(90 BYTE), 
	"START_DTTM" DATE, 
	"END_DTTM" DATE, 
	"SOURCE_ID" NUMBER, 
	"SYSTEM_ID" VARCHAR2(255 BYTE), 
	"UNIEWAZNIONY" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZASILEK_DETALE_TMP
--------------------------------------------------------

  CREATE TABLE "TEMP"."ZASILEK_DETALE_TMP" 
   (	"ID_ZASILEK_DETALE" NUMBER, 
	"KWOTA" NUMBER, 
	"DATA" DATE, 
	"NAZWA" VARCHAR2(90 BYTE), 
	"START_DTTM" DATE, 
	"END_DTTM" DATE, 
	"SOURCE_ID" NUMBER, 
	"SYSTEM_ID" VARCHAR2(255 BYTE), 
	"UNIEWAZNIONY" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZASILEK_TMP
--------------------------------------------------------

  CREATE TABLE "TEMP"."ZASILEK_TMP" 
   (	"ID_ZASILEK" NUMBER, 
	"ID_PRACOWNIK" NUMBER, 
	"ID_ZASILEK_DETALE" NUMBER, 
	"START_DTTM" DATE, 
	"END_DTTM" DATE, 
	"SOURCE_ID" NUMBER, 
	"SYSTEM_ID" VARCHAR2(255 BYTE), 
	"UNIEWAZNIONY" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
