--------------------------------------------------------
--  File created - czwartek-lipca-02-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table KLIENCI
--------------------------------------------------------

  CREATE TABLE "DWH"."KLIENCI" SHARING=METADATA 
   (	"ID_KLIENT" NUMBER, 
	"IMIE" VARCHAR2(60 BYTE), 
	"NAZWISKO" VARCHAR2(60 BYTE), 
	"ULICA" VARCHAR2(90 BYTE), 
	"NR_MIESZKANIA" VARCHAR2(20 BYTE), 
	"POCZTA" VARCHAR2(60 BYTE), 
	"NR_TELEFONU" VARCHAR2(11 BYTE), 
	"START_DTTM" DATE, 
	"END_DTTM" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KLIENCI_KEY
--------------------------------------------------------

  CREATE TABLE "DWH"."KLIENCI_KEY" SHARING=METADATA 
   (	"SOURCE_ID" NUMBER, 
	"SYSTEM" VARCHAR2(20 BYTE), 
	"ID" NUMBER, 
	"START_DTTM" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MAT_DO_RODZ_PRAC
--------------------------------------------------------

  CREATE TABLE "DWH"."MAT_DO_RODZ_PRAC" SHARING=METADATA 
   (	"ID" NUMBER, 
	"ID_RODZ_PRACY" NUMBER, 
	"ID_MATERIAL" NUMBER, 
	"ILOSC_MIN" NUMBER, 
	"ILOSC_MAX" NUMBER, 
	"START_DTTM" DATE, 
	"END_DTTM" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MAT_DO_RODZ_PRAC_KEY
--------------------------------------------------------

  CREATE TABLE "DWH"."MAT_DO_RODZ_PRAC_KEY" SHARING=METADATA 
   (	"SOURCE_ID" NUMBER, 
	"SYSTEM" VARCHAR2(20 BYTE), 
	"ID" NUMBER, 
	"START_DTTM" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MATERIALY
--------------------------------------------------------

  CREATE TABLE "DWH"."MATERIALY" SHARING=METADATA 
   (	"ID_MATERIAL" NUMBER, 
	"NAZWA" VARCHAR2(90 BYTE), 
	"JEDNOSTKA_MIARY" VARCHAR2(30 BYTE), 
	"KOSZT_JEDNOSTKI_MIARY" NUMBER, 
	"START_DTTM" DATE, 
	"END_DTTM" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MATERIALY_KEY
--------------------------------------------------------

  CREATE TABLE "DWH"."MATERIALY_KEY" SHARING=METADATA 
   (	"SOURCE_ID" NUMBER, 
	"SYSTEM" VARCHAR2(20 BYTE), 
	"ID" NUMBER, 
	"START_DTTM" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRACE_WYKONANE
--------------------------------------------------------

  CREATE TABLE "DWH"."PRACE_WYKONANE" SHARING=METADATA 
   (	"ID_PRACY_WYKONANEJ" NUMBER, 
	"ID_PRACOWNIK" NUMBER, 
	"ID_RODZ_PRACY" NUMBER, 
	"DATA_OD" DATE, 
	"DATA_DO" DATE, 
	"ILOSC_PRACY" NUMBER, 
	"START_DTTM" DATE, 
	"END_DTTM" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRACE_WYKONANE_KEY
--------------------------------------------------------

  CREATE TABLE "DWH"."PRACE_WYKONANE_KEY" SHARING=METADATA 
   (	"SOURCE_ID" NUMBER, 
	"SYSTEM" VARCHAR2(20 BYTE), 
	"ID" NUMBER, 
	"START_DTTM" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRACOWNICY
--------------------------------------------------------

  CREATE TABLE "DWH"."PRACOWNICY" SHARING=METADATA 
   (	"ID_PRACOWNIKA" NUMBER, 
	"IMIE" VARCHAR2(60 BYTE), 
	"NAZWISKO" VARCHAR2(2060 BYTE), 
	"DATA_ZATRUDNIENIA" DATE, 
	"DATA_ZWOLNIENIA" DATE, 
	"PESEL" VARCHAR2(11 BYTE), 
	"START_DTTM" DATE, 
	"END_DTTM" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRACOWNICY_KEY
--------------------------------------------------------

  CREATE TABLE "DWH"."PRACOWNICY_KEY" SHARING=METADATA 
   (	"SOURCE_ID" NUMBER, 
	"SYSTEM" VARCHAR2(20 BYTE), 
	"ID" NUMBER, 
	"START_DTTM" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PREMIA
--------------------------------------------------------

  CREATE TABLE "DWH"."PREMIA" SHARING=METADATA 
   (	"ID_PREMIA" NUMBER, 
	"ID_PRACOWNIK" NUMBER, 
	"WYSOKOSC" NUMBER, 
	"START_DTTM" DATE, 
	"END_DTTM" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PREMIA_KEY
--------------------------------------------------------

  CREATE TABLE "DWH"."PREMIA_KEY" SHARING=METADATA 
   (	"SOURCE_ID" NUMBER, 
	"SYSTEM" VARCHAR2(20 BYTE), 
	"ID" NUMBER, 
	"START_DTTM" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRZERWA_W_PRACY
--------------------------------------------------------

  CREATE TABLE "DWH"."PRZERWA_W_PRACY" SHARING=METADATA 
   (	"ID_PRZERW_W_PRACY" NUMBER, 
	"ID_PRACOWNIKA" NUMBER, 
	"ID_RODZAJ_PRZERWY" NUMBER, 
	"ID_UZASADNIENIA" NUMBER, 
	"CZAS_TRWANIA" NUMBER, 
	"START_DTTM" DATE, 
	"END_DTTM" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRZERWA_W_PRACY_KEY
--------------------------------------------------------

  CREATE TABLE "DWH"."PRZERWA_W_PRACY_KEY" SHARING=METADATA 
   (	"SOURCE_ID" NUMBER, 
	"SYSTEM" VARCHAR2(20 BYTE), 
	"ID" NUMBER, 
	"START_DTTM" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RODZAJE_PRAC
--------------------------------------------------------

  CREATE TABLE "DWH"."RODZAJE_PRAC" SHARING=METADATA 
   (	"ID_RODZ_PRACY" NUMBER, 
	"NAZWA" VARCHAR2(90 BYTE), 
	"JED_MIARY" VARCHAR2(20 BYTE), 
	"MIN_NORMA_NA_H" NUMBER, 
	"MAX_NORMA_NA_H" NUMBER, 
	"KOSZT_JED_MIARY" NUMBER, 
	"COLUMN7" DATE, 
	"END_DTTM" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RODZAJE_PRAC_KEY
--------------------------------------------------------

  CREATE TABLE "DWH"."RODZAJE_PRAC_KEY" SHARING=METADATA 
   (	"SOURCE_ID" NUMBER, 
	"SYSTEM" VARCHAR2(20 BYTE), 
	"ID" NUMBER, 
	"START_DTTM" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RODZAJ_PRZERWY
--------------------------------------------------------

  CREATE TABLE "DWH"."RODZAJ_PRZERWY" SHARING=METADATA 
   (	"ID_RODZAJ_PRZERWY" NUMBER, 
	"NAZWA" VARCHAR2(90 BYTE), 
	"START_DTTM" DATE, 
	"END_DTTM" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RODZAJ_PRZERWY_KEY
--------------------------------------------------------

  CREATE TABLE "DWH"."RODZAJ_PRZERWY_KEY" SHARING=METADATA 
   (	"SOURCE_ID" NUMBER, 
	"SYSTEM" VARCHAR2(20 BYTE), 
	"ID" NUMBER, 
	"START_DTTM" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table UZASADNIENIE
--------------------------------------------------------

  CREATE TABLE "DWH"."UZASADNIENIE" SHARING=METADATA 
   (	"ID_UZASADNIENIE" NUMBER, 
	"UZASADNIENIE" VARCHAR2(255 BYTE), 
	"START_DTTM" DATE, 
	"END_DTTM" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table UZASADNIENIE_KEY
--------------------------------------------------------

  CREATE TABLE "DWH"."UZASADNIENIE_KEY" SHARING=METADATA 
   (	"SOURCE_ID" NUMBER, 
	"SYSTEM" VARCHAR2(20 BYTE), 
	"ID" NUMBER, 
	"START_DTTM" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZAMOWIENIE
--------------------------------------------------------

  CREATE TABLE "DWH"."ZAMOWIENIE" SHARING=METADATA 
   (	"ID_ZAMOWIENIE" NUMBER, 
	"ID_KLIENT" NUMBER, 
	"ID_PRACOWNIK" NUMBER, 
	"DATA" DATE, 
	"START_DTTM" DATE, 
	"END_DTTM" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZAMOWIENIE_DETALE
--------------------------------------------------------

  CREATE TABLE "DWH"."ZAMOWIENIE_DETALE" SHARING=METADATA 
   (	"ID_ZAMOWIENIE" NUMBER, 
	"ID_MATERIAL" NUMBER, 
	"ILOSC" NUMBER, 
	"START_DTTM" DATE, 
	"END_DTTM" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZAMOWIENIE_DETALE_KEY
--------------------------------------------------------

  CREATE TABLE "DWH"."ZAMOWIENIE_DETALE_KEY" SHARING=METADATA 
   (	"SOURCE_ID" NUMBER, 
	"SYSTEM" VARCHAR2(20 BYTE), 
	"ID" NUMBER, 
	"START_DTTM" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZAMOWIENIE_KEY
--------------------------------------------------------

  CREATE TABLE "DWH"."ZAMOWIENIE_KEY" SHARING=METADATA 
   (	"SOURCE_ID" NUMBER, 
	"SYSTEM" VARCHAR2(20 BYTE), 
	"ID" NUMBER, 
	"START_DTTM" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZASILEK
--------------------------------------------------------

  CREATE TABLE "DWH"."ZASILEK" SHARING=METADATA 
   (	"ID_ZASILEK" NUMBER, 
	"ID_PRACOWNIK" NUMBER, 
	"ID_ZASILEK_DETALE" NUMBER, 
	"START_DTTM" DATE, 
	"END_DTTM" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZASILEK_DETALE
--------------------------------------------------------

  CREATE TABLE "DWH"."ZASILEK_DETALE" 
   (	"ID_ZASILEK_DETALE" NUMBER, 
	"KWOTA" NUMBER, 
	"DATA" DATE, 
	"NAZWA" VARCHAR2(90 BYTE), 
	"START_DTTM" DATE, 
	"END_DTTM" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZASILEK_DETALE_KEY
--------------------------------------------------------

  CREATE TABLE "DWH"."ZASILEK_DETALE_KEY" SHARING=METADATA 
   (	"SOURCE_ID" NUMBER, 
	"SYSTEM" VARCHAR2(20 BYTE), 
	"ID" NUMBER, 
	"START_DTTM" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZASILEK_KEY
--------------------------------------------------------

  CREATE TABLE "DWH"."ZASILEK_KEY" SHARING=METADATA 
   (	"SOURCE_ID" NUMBER, 
	"SYSTEM" VARCHAR2(20 BYTE), 
	"ID" NUMBER, 
	"START_DTTM" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZUZYCIE_MATERIALOW
--------------------------------------------------------

  CREATE TABLE "DWH"."ZUZYCIE_MATERIALOW" SHARING=METADATA 
   (	"ID_ZUZ_MAT" NUMBER, 
	"ID_PRACA_WYKONANA" NUMBER, 
	"ID_MATERIAL" NUMBER, 
	"START_DTTM" DATE, 
	"END_DTTM" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZUZYCIE_MATER_KEY
--------------------------------------------------------

  CREATE TABLE "DWH"."ZUZYCIE_MATER_KEY" SHARING=METADATA 
   (	"SOURCE_ID" NUMBER, 
	"SYSTEM" VARCHAR2(20 BYTE), 
	"ID" NUMBER, 
	"START_DTTM" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index KLIENT_KEY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DWH"."KLIENT_KEY_PK" ON "DWH"."KLIENCI_KEY" ("SOURCE_ID", "SYSTEM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MAT_DO_RODZ_PRAC_KEY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DWH"."MAT_DO_RODZ_PRAC_KEY_PK" ON "DWH"."MAT_DO_RODZ_PRAC_KEY" ("SOURCE_ID", "SYSTEM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MATERIALY_KEY_pk
--------------------------------------------------------

  CREATE UNIQUE INDEX "DWH"."MATERIALY_KEY_pk" ON "DWH"."MATERIALY_KEY" ("SOURCE_ID", "SYSTEM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRACE_WYKONANE_KEY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DWH"."PRACE_WYKONANE_KEY_PK" ON "DWH"."PRACE_WYKONANE_KEY" ("SOURCE_ID", "SYSTEM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRACOWNICY_KEY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DWH"."PRACOWNICY_KEY_PK" ON "DWH"."PRACOWNICY_KEY" ("SOURCE_ID", "SYSTEM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PREMIA_KEY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DWH"."PREMIA_KEY_PK" ON "DWH"."PREMIA_KEY" ("SOURCE_ID", "SYSTEM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRZERWA_W_PRACY_KEY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DWH"."PRZERWA_W_PRACY_KEY_PK" ON "DWH"."PRZERWA_W_PRACY_KEY" ("SOURCE_ID", "SYSTEM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RODZAJE_PRAC_KEY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DWH"."RODZAJE_PRAC_KEY_PK" ON "DWH"."RODZAJE_PRAC_KEY" ("SOURCE_ID", "SYSTEM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RODZAJ_PRZERWY_KEY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DWH"."RODZAJ_PRZERWY_KEY_PK" ON "DWH"."RODZAJ_PRZERWY_KEY" ("SOURCE_ID", "SYSTEM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UZASADNIENIE_KEY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DWH"."UZASADNIENIE_KEY_PK" ON "DWH"."UZASADNIENIE_KEY" ("SOURCE_ID", "SYSTEM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ZAMOWIENIE_DETALE_KEY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DWH"."ZAMOWIENIE_DETALE_KEY_PK" ON "DWH"."ZAMOWIENIE_DETALE_KEY" ("SOURCE_ID", "SYSTEM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ZAMOWIENIE_KEY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DWH"."ZAMOWIENIE_KEY_PK" ON "DWH"."ZAMOWIENIE_KEY" ("SOURCE_ID", "SYSTEM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ZASILEK_DETALE_KEY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DWH"."ZASILEK_DETALE_KEY_PK" ON "DWH"."ZASILEK_DETALE_KEY" ("SOURCE_ID", "SYSTEM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ZASILEK_KEY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DWH"."ZASILEK_KEY_PK" ON "DWH"."ZASILEK_KEY" ("SOURCE_ID", "SYSTEM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ZUZYCIE_MATER_KEY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DWH"."ZUZYCIE_MATER_KEY_PK" ON "DWH"."ZUZYCIE_MATER_KEY" ("SOURCE_ID", "SYSTEM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table KLIENCI
--------------------------------------------------------

  ALTER TABLE "DWH"."KLIENCI" MODIFY ("ID_KLIENT" NOT NULL ENABLE);
  ALTER TABLE "DWH"."KLIENCI" MODIFY ("IMIE" NOT NULL ENABLE);
  ALTER TABLE "DWH"."KLIENCI" MODIFY ("NAZWISKO" NOT NULL ENABLE);
  ALTER TABLE "DWH"."KLIENCI" MODIFY ("START_DTTM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."KLIENCI" MODIFY ("END_DTTM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KLIENCI_KEY
--------------------------------------------------------

  ALTER TABLE "DWH"."KLIENCI_KEY" MODIFY ("SOURCE_ID" NOT NULL ENABLE);
  ALTER TABLE "DWH"."KLIENCI_KEY" MODIFY ("SYSTEM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."KLIENCI_KEY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DWH"."KLIENCI_KEY" MODIFY ("START_DTTM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."KLIENCI_KEY" ADD CONSTRAINT "KLIENT_KEY_PK" PRIMARY KEY ("SOURCE_ID", "SYSTEM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MAT_DO_RODZ_PRAC
--------------------------------------------------------

  ALTER TABLE "DWH"."MAT_DO_RODZ_PRAC" MODIFY ("ID_RODZ_PRACY" NOT NULL ENABLE);
  ALTER TABLE "DWH"."MAT_DO_RODZ_PRAC" MODIFY ("ID_MATERIAL" NOT NULL ENABLE);
  ALTER TABLE "DWH"."MAT_DO_RODZ_PRAC" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DWH"."MAT_DO_RODZ_PRAC" MODIFY ("START_DTTM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."MAT_DO_RODZ_PRAC" MODIFY ("END_DTTM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MAT_DO_RODZ_PRAC_KEY
--------------------------------------------------------

  ALTER TABLE "DWH"."MAT_DO_RODZ_PRAC_KEY" MODIFY ("SOURCE_ID" NOT NULL ENABLE);
  ALTER TABLE "DWH"."MAT_DO_RODZ_PRAC_KEY" MODIFY ("SYSTEM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."MAT_DO_RODZ_PRAC_KEY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DWH"."MAT_DO_RODZ_PRAC_KEY" MODIFY ("START_DTTM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."MAT_DO_RODZ_PRAC_KEY" ADD CONSTRAINT "MAT_DO_RODZ_PRAC_KEY_PK" PRIMARY KEY ("SOURCE_ID", "SYSTEM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MATERIALY
--------------------------------------------------------

  ALTER TABLE "DWH"."MATERIALY" MODIFY ("ID_MATERIAL" NOT NULL ENABLE);
  ALTER TABLE "DWH"."MATERIALY" MODIFY ("NAZWA" NOT NULL ENABLE);
  ALTER TABLE "DWH"."MATERIALY" MODIFY ("START_DTTM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."MATERIALY" MODIFY ("END_DTTM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MATERIALY_KEY
--------------------------------------------------------

  ALTER TABLE "DWH"."MATERIALY_KEY" MODIFY ("SOURCE_ID" NOT NULL ENABLE);
  ALTER TABLE "DWH"."MATERIALY_KEY" MODIFY ("SYSTEM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."MATERIALY_KEY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DWH"."MATERIALY_KEY" MODIFY ("START_DTTM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."MATERIALY_KEY" ADD CONSTRAINT "MATERIALY_KEY_pk" PRIMARY KEY ("SOURCE_ID", "SYSTEM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRACE_WYKONANE
--------------------------------------------------------

  ALTER TABLE "DWH"."PRACE_WYKONANE" MODIFY ("ID_PRACOWNIK" NOT NULL ENABLE);
  ALTER TABLE "DWH"."PRACE_WYKONANE" MODIFY ("ID_RODZ_PRACY" NOT NULL ENABLE);
  ALTER TABLE "DWH"."PRACE_WYKONANE" MODIFY ("ID_PRACY_WYKONANEJ" NOT NULL ENABLE);
  ALTER TABLE "DWH"."PRACE_WYKONANE" MODIFY ("START_DTTM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."PRACE_WYKONANE" MODIFY ("END_DTTM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRACE_WYKONANE_KEY
--------------------------------------------------------

  ALTER TABLE "DWH"."PRACE_WYKONANE_KEY" MODIFY ("SOURCE_ID" NOT NULL ENABLE);
  ALTER TABLE "DWH"."PRACE_WYKONANE_KEY" MODIFY ("SYSTEM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."PRACE_WYKONANE_KEY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DWH"."PRACE_WYKONANE_KEY" MODIFY ("START_DTTM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."PRACE_WYKONANE_KEY" ADD CONSTRAINT "PRACE_WYKONANE_KEY_PK" PRIMARY KEY ("SOURCE_ID", "SYSTEM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRACOWNICY
--------------------------------------------------------

  ALTER TABLE "DWH"."PRACOWNICY" MODIFY ("ID_PRACOWNIKA" NOT NULL ENABLE);
  ALTER TABLE "DWH"."PRACOWNICY" MODIFY ("START_DTTM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."PRACOWNICY" MODIFY ("END_DTTM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRACOWNICY_KEY
--------------------------------------------------------

  ALTER TABLE "DWH"."PRACOWNICY_KEY" MODIFY ("SOURCE_ID" NOT NULL ENABLE);
  ALTER TABLE "DWH"."PRACOWNICY_KEY" MODIFY ("SYSTEM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."PRACOWNICY_KEY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DWH"."PRACOWNICY_KEY" MODIFY ("START_DTTM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."PRACOWNICY_KEY" ADD CONSTRAINT "PRACOWNICY_KEY_PK" PRIMARY KEY ("SOURCE_ID", "SYSTEM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PREMIA
--------------------------------------------------------

  ALTER TABLE "DWH"."PREMIA" MODIFY ("ID_PREMIA" NOT NULL ENABLE);
  ALTER TABLE "DWH"."PREMIA" MODIFY ("ID_PRACOWNIK" NOT NULL ENABLE);
  ALTER TABLE "DWH"."PREMIA" MODIFY ("START_DTTM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."PREMIA" MODIFY ("END_DTTM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PREMIA_KEY
--------------------------------------------------------

  ALTER TABLE "DWH"."PREMIA_KEY" MODIFY ("SOURCE_ID" NOT NULL ENABLE);
  ALTER TABLE "DWH"."PREMIA_KEY" MODIFY ("SYSTEM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."PREMIA_KEY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DWH"."PREMIA_KEY" MODIFY ("START_DTTM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."PREMIA_KEY" ADD CONSTRAINT "PREMIA_KEY_PK" PRIMARY KEY ("SOURCE_ID", "SYSTEM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRZERWA_W_PRACY
--------------------------------------------------------

  ALTER TABLE "DWH"."PRZERWA_W_PRACY" MODIFY ("ID_PRZERW_W_PRACY" NOT NULL ENABLE);
  ALTER TABLE "DWH"."PRZERWA_W_PRACY" MODIFY ("ID_PRACOWNIKA" NOT NULL ENABLE);
  ALTER TABLE "DWH"."PRZERWA_W_PRACY" MODIFY ("ID_RODZAJ_PRZERWY" NOT NULL ENABLE);
  ALTER TABLE "DWH"."PRZERWA_W_PRACY" MODIFY ("START_DTTM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."PRZERWA_W_PRACY" MODIFY ("END_DTTM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRZERWA_W_PRACY_KEY
--------------------------------------------------------

  ALTER TABLE "DWH"."PRZERWA_W_PRACY_KEY" MODIFY ("SOURCE_ID" NOT NULL ENABLE);
  ALTER TABLE "DWH"."PRZERWA_W_PRACY_KEY" MODIFY ("SYSTEM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."PRZERWA_W_PRACY_KEY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DWH"."PRZERWA_W_PRACY_KEY" MODIFY ("START_DTTM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."PRZERWA_W_PRACY_KEY" ADD CONSTRAINT "PRZERWA_W_PRACY_KEY_PK" PRIMARY KEY ("SOURCE_ID", "SYSTEM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RODZAJE_PRAC
--------------------------------------------------------

  ALTER TABLE "DWH"."RODZAJE_PRAC" MODIFY ("NAZWA" NOT NULL ENABLE);
  ALTER TABLE "DWH"."RODZAJE_PRAC" MODIFY ("END_DTTM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."RODZAJE_PRAC" MODIFY ("ID_RODZ_PRACY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RODZAJE_PRAC_KEY
--------------------------------------------------------

  ALTER TABLE "DWH"."RODZAJE_PRAC_KEY" MODIFY ("SOURCE_ID" NOT NULL ENABLE);
  ALTER TABLE "DWH"."RODZAJE_PRAC_KEY" MODIFY ("SYSTEM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."RODZAJE_PRAC_KEY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DWH"."RODZAJE_PRAC_KEY" MODIFY ("START_DTTM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."RODZAJE_PRAC_KEY" ADD CONSTRAINT "RODZAJE_PRAC_KEY_PK" PRIMARY KEY ("SOURCE_ID", "SYSTEM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RODZAJ_PRZERWY
--------------------------------------------------------

  ALTER TABLE "DWH"."RODZAJ_PRZERWY" MODIFY ("NAZWA" NOT NULL ENABLE);
  ALTER TABLE "DWH"."RODZAJ_PRZERWY" MODIFY ("START_DTTM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."RODZAJ_PRZERWY" MODIFY ("END_DTTM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."RODZAJ_PRZERWY" MODIFY ("ID_RODZAJ_PRZERWY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RODZAJ_PRZERWY_KEY
--------------------------------------------------------

  ALTER TABLE "DWH"."RODZAJ_PRZERWY_KEY" MODIFY ("SOURCE_ID" NOT NULL ENABLE);
  ALTER TABLE "DWH"."RODZAJ_PRZERWY_KEY" MODIFY ("SYSTEM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."RODZAJ_PRZERWY_KEY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DWH"."RODZAJ_PRZERWY_KEY" MODIFY ("START_DTTM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."RODZAJ_PRZERWY_KEY" ADD CONSTRAINT "RODZAJ_PRZERWY_KEY_PK" PRIMARY KEY ("SOURCE_ID", "SYSTEM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table UZASADNIENIE
--------------------------------------------------------

  ALTER TABLE "DWH"."UZASADNIENIE" MODIFY ("START_DTTM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."UZASADNIENIE" MODIFY ("END_DTTM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."UZASADNIENIE" MODIFY ("ID_UZASADNIENIE" NOT NULL ENABLE);
  ALTER TABLE "DWH"."UZASADNIENIE" MODIFY ("UZASADNIENIE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table UZASADNIENIE_KEY
--------------------------------------------------------

  ALTER TABLE "DWH"."UZASADNIENIE_KEY" MODIFY ("SOURCE_ID" NOT NULL ENABLE);
  ALTER TABLE "DWH"."UZASADNIENIE_KEY" MODIFY ("SYSTEM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."UZASADNIENIE_KEY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DWH"."UZASADNIENIE_KEY" MODIFY ("START_DTTM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."UZASADNIENIE_KEY" ADD CONSTRAINT "UZASADNIENIE_KEY_PK" PRIMARY KEY ("SOURCE_ID", "SYSTEM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ZAMOWIENIE
--------------------------------------------------------

  ALTER TABLE "DWH"."ZAMOWIENIE" MODIFY ("ID_KLIENT" NOT NULL ENABLE);
  ALTER TABLE "DWH"."ZAMOWIENIE" MODIFY ("ID_PRACOWNIK" NOT NULL ENABLE);
  ALTER TABLE "DWH"."ZAMOWIENIE" MODIFY ("DATA" NOT NULL ENABLE);
  ALTER TABLE "DWH"."ZAMOWIENIE" MODIFY ("ID_ZAMOWIENIE" NOT NULL ENABLE);
  ALTER TABLE "DWH"."ZAMOWIENIE" MODIFY ("START_DTTM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."ZAMOWIENIE" MODIFY ("END_DTTM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ZAMOWIENIE_DETALE
--------------------------------------------------------

  ALTER TABLE "DWH"."ZAMOWIENIE_DETALE" MODIFY ("ID_MATERIAL" NOT NULL ENABLE);
  ALTER TABLE "DWH"."ZAMOWIENIE_DETALE" MODIFY ("START_DTTM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."ZAMOWIENIE_DETALE" MODIFY ("END_DTTM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."ZAMOWIENIE_DETALE" MODIFY ("ID_ZAMOWIENIE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ZAMOWIENIE_DETALE_KEY
--------------------------------------------------------

  ALTER TABLE "DWH"."ZAMOWIENIE_DETALE_KEY" MODIFY ("SOURCE_ID" NOT NULL ENABLE);
  ALTER TABLE "DWH"."ZAMOWIENIE_DETALE_KEY" MODIFY ("SYSTEM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."ZAMOWIENIE_DETALE_KEY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DWH"."ZAMOWIENIE_DETALE_KEY" MODIFY ("START_DTTM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."ZAMOWIENIE_DETALE_KEY" ADD CONSTRAINT "ZAMOWIENIE_DETALE_KEY_PK" PRIMARY KEY ("SOURCE_ID", "SYSTEM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ZAMOWIENIE_KEY
--------------------------------------------------------

  ALTER TABLE "DWH"."ZAMOWIENIE_KEY" MODIFY ("SOURCE_ID" NOT NULL ENABLE);
  ALTER TABLE "DWH"."ZAMOWIENIE_KEY" MODIFY ("SYSTEM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."ZAMOWIENIE_KEY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DWH"."ZAMOWIENIE_KEY" MODIFY ("START_DTTM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."ZAMOWIENIE_KEY" ADD CONSTRAINT "ZAMOWIENIE_KEY_PK" PRIMARY KEY ("SOURCE_ID", "SYSTEM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ZASILEK
--------------------------------------------------------

  ALTER TABLE "DWH"."ZASILEK" MODIFY ("ID_ZASILEK" NOT NULL ENABLE);
  ALTER TABLE "DWH"."ZASILEK" MODIFY ("ID_PRACOWNIK" NOT NULL ENABLE);
  ALTER TABLE "DWH"."ZASILEK" MODIFY ("ID_ZASILEK_DETALE" NOT NULL ENABLE);
  ALTER TABLE "DWH"."ZASILEK" MODIFY ("START_DTTM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."ZASILEK" MODIFY ("END_DTTM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ZASILEK_DETALE
--------------------------------------------------------

  ALTER TABLE "DWH"."ZASILEK_DETALE" MODIFY ("START_DTTM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."ZASILEK_DETALE" MODIFY ("END_DTTM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ZASILEK_DETALE_KEY
--------------------------------------------------------

  ALTER TABLE "DWH"."ZASILEK_DETALE_KEY" MODIFY ("SOURCE_ID" NOT NULL ENABLE);
  ALTER TABLE "DWH"."ZASILEK_DETALE_KEY" MODIFY ("SYSTEM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."ZASILEK_DETALE_KEY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DWH"."ZASILEK_DETALE_KEY" MODIFY ("START_DTTM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."ZASILEK_DETALE_KEY" ADD CONSTRAINT "ZASILEK_DETALE_KEY_PK" PRIMARY KEY ("SOURCE_ID", "SYSTEM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ZASILEK_KEY
--------------------------------------------------------

  ALTER TABLE "DWH"."ZASILEK_KEY" MODIFY ("SOURCE_ID" NOT NULL ENABLE);
  ALTER TABLE "DWH"."ZASILEK_KEY" MODIFY ("SYSTEM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."ZASILEK_KEY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DWH"."ZASILEK_KEY" MODIFY ("START_DTTM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."ZASILEK_KEY" ADD CONSTRAINT "ZASILEK_KEY_PK" PRIMARY KEY ("SOURCE_ID", "SYSTEM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ZUZYCIE_MATERIALOW
--------------------------------------------------------

  ALTER TABLE "DWH"."ZUZYCIE_MATERIALOW" MODIFY ("ID_ZUZ_MAT" NOT NULL ENABLE);
  ALTER TABLE "DWH"."ZUZYCIE_MATERIALOW" MODIFY ("ID_PRACA_WYKONANA" NOT NULL ENABLE);
  ALTER TABLE "DWH"."ZUZYCIE_MATERIALOW" MODIFY ("ID_MATERIAL" NOT NULL ENABLE);
  ALTER TABLE "DWH"."ZUZYCIE_MATERIALOW" MODIFY ("START_DTTM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."ZUZYCIE_MATERIALOW" MODIFY ("END_DTTM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ZUZYCIE_MATER_KEY
--------------------------------------------------------

  ALTER TABLE "DWH"."ZUZYCIE_MATER_KEY" MODIFY ("SOURCE_ID" NOT NULL ENABLE);
  ALTER TABLE "DWH"."ZUZYCIE_MATER_KEY" MODIFY ("SYSTEM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."ZUZYCIE_MATER_KEY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DWH"."ZUZYCIE_MATER_KEY" MODIFY ("START_DTTM" NOT NULL ENABLE);
  ALTER TABLE "DWH"."ZUZYCIE_MATER_KEY" ADD CONSTRAINT "ZUZYCIE_MATER_KEY_PK" PRIMARY KEY ("SOURCE_ID", "SYSTEM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
