--------------------------------------------------------
--  File created - czwartek-lipca-02-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CSV_KLIENCI
--------------------------------------------------------

  CREATE TABLE "STAGE"."CSV_KLIENCI" 
   (	"ID" NUMBER, 
	"IMIE" VARCHAR2(255 BYTE), 
	"NAZWISKO" VARCHAR2(255 BYTE), 
	"PESEL" NUMBER, 
	"DATA_URODZENIA" DATE, 
	"WOJEWODZTWO" VARCHAR2(255 BYTE), 
	"ULICA" VARCHAR2(255 BYTE), 
	"NR_MIESZKANIA" VARCHAR2(255 BYTE), 
	"POCZTA" VARCHAR2(255 BYTE), 
	"MIEJSCOWOSC" VARCHAR2(255 BYTE), 
	"NR_TELEFONU" VARCHAR2(255 BYTE), 
	"EMAIL" VARCHAR2(255 BYTE), 
	"NEWSLETTER" VARCHAR2(255 BYTE), 
	"UNIEWAZNIONY" VARCHAR2(2 BYTE), 
	"TIMESTAMP" TIMESTAMP (6), 
	"SYSTEM_ID" VARCHAR2(255 BYTE), 
	"ACTIVE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CSV_PRACOWNICY
--------------------------------------------------------

  CREATE TABLE "STAGE"."CSV_PRACOWNICY" 
   (	"ID" NUMBER, 
	"IMIE" VARCHAR2(255 BYTE), 
	"NAZWISKO" VARCHAR2(255 BYTE), 
	"PESEL" NUMBER, 
	"DATA_URODZENIA" DATE, 
	"WOJEWODZTWO" VARCHAR2(1000 BYTE), 
	"ULICA" VARCHAR2(255 BYTE), 
	"NR_MIESZKANIA" VARCHAR2(255 BYTE), 
	"POCZTA" VARCHAR2(255 BYTE), 
	"MIEJSCOWOSC" VARCHAR2(255 BYTE), 
	"NR_TELEFONU" VARCHAR2(255 BYTE), 
	"EMAIL" VARCHAR2(255 BYTE), 
	"DATA_ZATRUDNIENIA" DATE, 
	"DATA_ZWOLNIENIA" DATE, 
	"PREMIA" NUMBER, 
	"UNIEWAZNIONY" VARCHAR2(5 BYTE), 
	"TIMESTAMP" TIMESTAMP (6), 
	"SYSTEM_ID" VARCHAR2(255 BYTE), 
	"ACTIVE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CSV_PREMIA
--------------------------------------------------------

  CREATE TABLE "STAGE"."CSV_PREMIA" 
   (	"ID" NUMBER, 
	"ID_PRACOWNIK" NUMBER, 
	"PREMIA" NUMBER, 
	"UNIEWAZNIONY" VARCHAR2(5 BYTE), 
	"TIMESTAMP" TIMESTAMP (6), 
	"SYSTEM_ID" VARCHAR2(255 BYTE), 
	"ACTIVE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CSV_ZAMOWIENIA
--------------------------------------------------------

  CREATE TABLE "STAGE"."CSV_ZAMOWIENIA" 
   (	"ID" NUMBER, 
	"ID_POZYCJA" NUMBER, 
	"IMIE" VARCHAR2(255 BYTE), 
	"NAZWISKO" VARCHAR2(255 BYTE), 
	"PESEL" NUMBER, 
	"DATA_URODZENIA" DATE, 
	"WOJEWODZTWO" VARCHAR2(255 BYTE), 
	"ULICA" VARCHAR2(255 BYTE), 
	"NR_MIESZKANIA" VARCHAR2(255 BYTE), 
	"POCZTA" VARCHAR2(255 BYTE), 
	"MIEJSCOWOSC" VARCHAR2(255 BYTE), 
	"NR_TELEFONU" VARCHAR2(255 BYTE), 
	"EMAIL" VARCHAR2(255 BYTE), 
	"NEWSLETTER" VARCHAR2(255 BYTE), 
	"ID_KLIENTA" NUMBER, 
	"ID_PRACOWNIKA" NUMBER, 
	"ID_MATERIALU" NUMBER, 
	"NAZWA_MATERIALU" VARCHAR2(255 BYTE), 
	"ILOSC_MATERIALU" NUMBER, 
	"DATA_ZAMOWIENIA" DATE, 
	"DATA_REALIZACJI" DATE, 
	"UNIEWAZNIONY" VARCHAR2(2 BYTE), 
	"TIMESTAMP" TIMESTAMP (6), 
	"SYSTEM_ID" VARCHAR2(255 BYTE), 
	"ACTIVE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CSV_ZASILKI
--------------------------------------------------------

  CREATE TABLE "STAGE"."CSV_ZASILKI" 
   (	"ID" NUMBER, 
	"ID_PRACOWNIK" NUMBER, 
	"ZASILEK_DETALE" NUMBER, 
	"DATA_PRZYZNANIA" DATE, 
	"UNIEWAZNIONY" VARCHAR2(5 BYTE), 
	"TIMESTAMP" TIMESTAMP (6), 
	"SYSTEM_ID" VARCHAR2(255 BYTE), 
	"ACTIVE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CSV_ZASILKI_DETALE
--------------------------------------------------------

  CREATE TABLE "STAGE"."CSV_ZASILKI_DETALE" 
   (	"ID" NUMBER, 
	"KWOTA" NUMBER, 
	"DATA_PRZYZNANIA" DATE, 
	"NAZWA" VARCHAR2(255 BYTE), 
	"UNIEWAZNIONY" VARCHAR2(5 BYTE), 
	"TIMESTAMP" TIMESTAMP (6), 
	"SYSTEM_ID" VARCHAR2(255 BYTE), 
	"ACTIVE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SOURCE2_PRACOWNICY
--------------------------------------------------------

  CREATE TABLE "STAGE"."SOURCE2_PRACOWNICY" 
   (	"ID_PRACOWNIKA" NUMBER, 
	"IMIE" VARCHAR2(60 BYTE), 
	"NAZWISKO" VARCHAR2(2060 BYTE), 
	"DATA_ZATRUDNIENIA" DATE, 
	"DATA_ZWOLNIENIA" DATE, 
	"PESEL" VARCHAR2(11 BYTE), 
	"UNIEWAZNIONY" VARCHAR2(5 BYTE), 
	"TIMESTAMP" TIMESTAMP (6), 
	"SYSTEM_ID" VARCHAR2(255 BYTE), 
	"ACTIVE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SOURCE2_PREMIA
--------------------------------------------------------

  CREATE TABLE "STAGE"."SOURCE2_PREMIA" 
   (	"ID_PREMIA" NUMBER, 
	"ID_PRACOWNIK" NUMBER, 
	"WYSOKOSC" NUMBER, 
	"UNIEWAZNIONY" VARCHAR2(5 BYTE), 
	"TIMESTAMP" TIMESTAMP (6), 
	"SYSTEM_ID" VARCHAR2(255 BYTE), 
	"ACTIVE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SOURCE2_ZASILEK
--------------------------------------------------------

  CREATE TABLE "STAGE"."SOURCE2_ZASILEK" 
   (	"ID_ZASILEK" NUMBER, 
	"ID_PRACOWNIK" NUMBER, 
	"ID_ZASILEK_DETALE" NUMBER, 
	"UNIEWAZNIONY" VARCHAR2(5 BYTE), 
	"TIMESTAMP" TIMESTAMP (6), 
	"SYSTEM_ID" VARCHAR2(255 BYTE), 
	"ACTIVE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SOURCE2_ZASILEK_DETALE
--------------------------------------------------------

  CREATE TABLE "STAGE"."SOURCE2_ZASILEK_DETALE" 
   (	"ID_ZASILEK_DETALE" NUMBER, 
	"KWOTA" NUMBER, 
	"DATA" DATE, 
	"NAZWA" VARCHAR2(90 BYTE), 
	"UNIEWAZNIONY" VARCHAR2(5 BYTE), 
	"TIMESTAMP" TIMESTAMP (6), 
	"SYSTEM_ID" VARCHAR2(255 BYTE), 
	"ACTIVE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table SOURCE2_PRACOWNICY
--------------------------------------------------------

  ALTER TABLE "STAGE"."SOURCE2_PRACOWNICY" MODIFY ("ID_PRACOWNIKA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SOURCE2_PREMIA
--------------------------------------------------------

  ALTER TABLE "STAGE"."SOURCE2_PREMIA" MODIFY ("ID_PREMIA" NOT NULL ENABLE);
  ALTER TABLE "STAGE"."SOURCE2_PREMIA" MODIFY ("ID_PRACOWNIK" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SOURCE2_ZASILEK
--------------------------------------------------------

  ALTER TABLE "STAGE"."SOURCE2_ZASILEK" MODIFY ("ID_ZASILEK" NOT NULL ENABLE);
  ALTER TABLE "STAGE"."SOURCE2_ZASILEK" MODIFY ("ID_PRACOWNIK" NOT NULL ENABLE);
  ALTER TABLE "STAGE"."SOURCE2_ZASILEK" MODIFY ("ID_ZASILEK_DETALE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SOURCE2_ZASILEK_DETALE
--------------------------------------------------------

  ALTER TABLE "STAGE"."SOURCE2_ZASILEK_DETALE" MODIFY ("ID_ZASILEK_DETALE" NOT NULL ENABLE);
