--------------------------------------------------------
--  DDL for Package HD
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE "SYS"."HD" IS 
    
    TYPE T_COLUMNS IS TABLE OF VARCHAR2(1000);
    TYPE T_TAB_COLUMNS IS TABLE OF T_COLUMNS;

    ------ UMOZLIWIA ZALADOWANIE DANYCH Z PLIKU CSV DO TABELI
    PROCEDURE FROM_CSV_TO_TABLE(V_SOURCE IN VARCHAR2, V_TABLE_NAME IN VARCHAR2, V_PATH IN VARCHAR2);
    
    ------ GENERUJE ID REKORDU W DOCELOWEJ TABELI HURTOWNI DOCELOWEJ
    ---------------------------
    -- P_SOURCE_ID - ID Z DANYCH ZRODLOWYCH
    -- P_SYSTEM_ID - SYSTEM(NAZWA SYSTEMU) Z KTOREGO POCHODZI DANY REKORD
    -- P_TARGET - DOCELOWA TABELA HURTOWNI
    FUNCTION GENERETE_DATAW_ID(P_SOURCE_ID IN number, P_SYSTEM_ID IN VARCHAR2, P_TARGET IN VARCHAR2) RETURN NUMBER;
    
    ------ ZALADOWANIE DANYCH DO STAGE ZE ZRODLA W POSTACI TABELI (SCHEMAT SOURCE)
    ---------------------------
    -- V_SOURCE - NAZWA TABELI ZRODLOWEJ
    -- V_INTO_SCHEMA - NAZWA DOCELOWEGO SCHEMATU
    PROCEDURE GET_DATA_FROM_SOURCE(V_SOURCE IN VARCHAR2, V_INTO_SCHEMA IN VARCHAR2);
    
    ------ UMOZLIWA UTWORZENIE SCHEMATU(UZYTKOWNIKA)
    -- UWAGA! 
    -- PONOWNE UZYCIE Z ISTNIEJACYM SCHEMATEM SPOWODUJE JEGO WYCZYSZCZENIE
    PROCEDURE CREATE_SCHEMA(PI_USERNAME IN NVARCHAR2,PI_PASSWORD IN NVARCHAR2);
    
    PROCEDURE SENT_DATA(V_SOURCE IN VARCHAR2, V_INTO_SCHEMA IN VARCHAR2);
    
    PROCEDURE CREATE_TEMPORARY(V_TARGET_TABLE VARCHAR2);
    
    FUNCTION F_CONVERT(P_LIST IN VARCHAR2) RETURN T_COLUMNS;
    
    function table_exists(p_table_name IN VARCHAR2, p_owner IN VARCHAR2) return number;
    
    FUNCTION IS_NULL_IN_ROW(p_table_name IN VARCHAR2, p_owner IN VARCHAR2, p_uniq IN VARCHAR2)RETURN varchar2;
    FUNCTION return_columns_names(p_table_name IN VARCHAR2, p_owner IN VARCHAR2, p_uniq IN VARCHAR2)RETURN varchar2;
    FUNCTION return_columns(p_table_name IN VARCHAR2, p_owner IN VARCHAR2, p_uniq IN VARCHAR2)RETURN SYS_REFCURSOR;
    FUNCTION INSERT_NULL_ROW_TO_BAD(p_target IN VARCHAR2, p_table_name IN VARCHAR2, p_owner IN VARCHAR2, p_uniq IN VARCHAR2)RETURN varchar2;


END HD;

/
